//related types!!
export const DETECT_GENDER_SUCCESS = "DETECT_GENDER_SUCCESS";
export const DETECT_GENDER_FAILURE = "DETECT_GENDER_FAILURE";

export const CLEAR_LIVE_CHAT_LOGS = "CLEAR_LIVE_CHAT_LOGS";

export const HANDLE_IDENTITY_CHANGE = "HANDLE_IDENTITY_CHANGE";

export const SERVER_IS_OPERATIONAL_SUCCESS = "SERVER_IS_OPERATIONAL_SUCCESS";
export const SERVER_IS_OPERATIONAL_FAILURE = "SERVER_IS_OPERATIONAL_FAILURE";
