//related types!!
export const DETECT_GENDER_SUCCESS = "DETECT_GENDER_SUCCESS";
export const DETECT_GENDER_FAILURE = "DETECT_GENDER_FAILURE";
export const CLEAR_LIVE_CHAT_LOGS = "CLEAR_LIVE_CHAT_LOGS";
