//related types!!
export const DETECT_GENDER_SUCCESS = "DETECT_GENDER_SUCCESS";
export const DETECT_GENDER_FAILURE = "DETECT_GENDER_FAILURE";

export const CLEAR_LIVE_CHAT_LOGS = "CLEAR_LIVE_CHAT_LOGS";

export const HANDLE_IDENTITY_CHANGE = "HANDLE_IDENTITY_CHANGE";

export const SERVER_IS_OPERATIONAL_SUCCESS = "SERVER_IS_OPERATIONAL_SUCCESS";
export const SERVER_IS_OPERATIONAL_FAILURE = "SERVER_IS_OPERATIONAL_FAILURE";

export const GET_TRENDS_SUCCESS = "GET_TRENDS_SUCCESS";
export const GET_TRENDS_FAILURE = "GET_TRENDS_FAILURE";

export const GET_WISH_CATEGORIES_SUCCESS = "GET_WISH_CATEGORIES_SUCCESS";
export const GET_WISH_CATEGORIES_FAILURE = "GET_WISH_CATEGORIES_FAILURE";

export const SAVE_NEW_WISH_TEMPLATE_SUCCESS = "SAVE_NEW_WISH_TEMPLATE_SUCCESS";
export const SAVE_NEW_WISH_TEMPLATE_FAILURE = "SAVE_NEW_WISH_TEMPLATE_FAILURE";

export const GET_WISH_TEMPLATES_SUCCESS = "GET_WISH_TEMPLATES_SUCCESS";
export const GET_WISH_TEMPLATES_FAILURE = "GET_WISH_TEMPLATES_FAILURE";

export const ADD_NOTIFY_TOKEN_SUCCESS = "ADD_NOTIFY_TOKEN_SUCCESS";
export const ADD_NOTIFY_TOKEN_FAILURE = "ADD_NOTIFY_TOKEN_FAILURE";

export const CLEAR_WISHES = "CLEAR_WISHES";
